# Generated by Django 5.0.4 on 2024-05-27 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masseges', '0005_conversation_chat_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anser',
            new_name='Answer',
        ),
    ]
