# Generated by Django 5.0.4 on 2024-05-27 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masseges', '0007_rename_anser_conversation_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='anser',
            new_name='answer',
        ),
    ]
