# Generated by Django 5.0.3 on 2024-03-30 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_choise_text_choice_choice_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 3, 30, 7, 0, 23, 971847, tzinfo=datetime.timezone.utc)),
        ),
    ]
