# Generated by Django 5.0.3 on 2024-04-03 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_question_pub_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
